select * from customer limit 20

-- Q1 what is the total revenue generated by sale vs female customers?
SELECT gender,SUM(purchase_amount) AS total_revenue FROM customer group by gender

-- Q2 Whuch customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id,
    item_purchased,
    purchase_amount,
    discount_applied
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount > (
        SELECT AVG(purchase_amount)
        FROM customer
);

-- Q3 Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating::numeric),2) AS avg_review_rating  -- round off is not applicable for double precision ( review_rating)
	                                                    -- thats why we wrote numeric and we are rounding it off to 2 places 
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4 Comapre the average purchase amounts between standard and express shipping?
SELECT          -- dataset me exact Standard nahi hai, multiple shipping types hain, Saare compare karte hain
    shipping_type,
    ROUND(AVG(purchase_amount),2) 
FROM customer 
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type

-- Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non- subscribers?
SELECT 
    subscription_status,
    COUNT(customer_id) as total_customers,
	ROUND(AVG(purchase_amount),2) AS avg_spend,
    ROUND(SUM(purchase_amount),2) AS total_revenue  
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend desc;

-- Q6 Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,  -- instead of looking at total discount we have to calculate discunt rate per product
FROM customer
        ROUND(100 * SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7 Segment customers into new, returning and loyal based on their total number of previous purchases, and show the count of each segment.
  -- (Condition based on previous_purchases New = 1, Returning = 2 to 10, Loyal = >10)
WITH customer_type as(
SELECT customer_id,previous_purchases,
CASE 
        WHEN previous_purchases=1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
        END AS customer_segment
FROM customer
)
SELECT customer_segment,COUNT(*) AS "Number of customers"
FROM customer_type
GROUP BY customer_segment

-- Q8 What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
		ROW_NUMBER() over (partition by category order by count(customer_id) desc) as item_rank
		-- instead of rank and dense rank function of window function we used row_num func bcoz for many items the numbers are 
		-- same and other two function would have put sunglasses and belt in rank 2
    FROM customer
    GROUP BY category, item_purchased
)

SELECT item_rank,category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9 Are the customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status,
    COUNT(*) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
-- for percentage:
SELECT 
    subscription_status,
    ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM customer WHERE previous_purchases > 5),2) AS percentage_repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10 What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue,
    ROUND(100.0 * SUM(purchase_amount)/(SELECT SUM(purchase_amount) FROM customer),2) AS revenue_percentage
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;